name: Build sbom projects
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.save_sbom.outputs.test }}
    name: Create SBOM and pass it to api
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - name: Create SBOM with CycloneDX
        id: sbom
        uses: CycloneDX/gh-node-module-generatebom@master 
        with:
            output: './test.app.bom.json'
      - name: Print user email id
        run: |
          echo  ${{github.event.pusher.email}}  
      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ github.triggering_actor }}
      
        # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.test.outputs.email }}"
