name: Build sbom projects
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.save_sbom.outputs.test }}
    name: Create SBOM and pass it to api
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - name: Create SBOM with CycloneDX
        id: sbom
        uses: CycloneDX/gh-node-module-generatebom@master 
        with:
            output: './test.app.bom.json'
      - name: Print user email id
        run: |
          echo  ${{github.event.pusher.email}}  
      - name: get email
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/Rincy88
